/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente.GUI;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author bwosi
 */
public class MenuAdm extends javax.swing.JFrame {

    private Socket socket;
    private PrintWriter output;
    private BufferedReader input;
    private String token;
    private String perfil;
    
    /**
     * Creates new form MenuAdm
     */
    public MenuAdm(Socket socket, PrintWriter output, BufferedReader input, String token, String perfil) {
        initComponents();
        this.socket = socket;
        this.input = input;
        this.output = output;
        this.token = token;
        this.perfil = perfil;
    }

    private MenuAdm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrarNovoUsuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();
        btnListarUsuarios = new javax.swing.JButton();
        btnCadastrarOrdem = new javax.swing.JButton();
        btnListarOrdem = new javax.swing.JButton();
        btnAlterarOrdem = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCadastrarNovoUsuario.setText("Cadastrar novo usuario");

        btnEditarUsuario.setText("Editar usuario");

        btnExcluirUsuario.setText("Excluir usuario");

        btnListarUsuarios.setText("Listar usuarios");

        btnCadastrarOrdem.setText("Cadastrar ordem de serviço");
        btnCadastrarOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarOrdemActionPerformed(evt);
            }
        });

        btnListarOrdem.setText("Listar ordens de serviço");
        btnListarOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarOrdemActionPerformed(evt);
            }
        });

        btnAlterarOrdem.setText("Alterar Ordem de Serviço");
        btnAlterarOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarOrdemActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarUsuario)
                    .addComponent(btnCadastrarNovoUsuario)
                    .addComponent(btnListarUsuarios)
                    .addComponent(btnExcluirUsuario)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrarOrdem)
                    .addComponent(btnListarOrdem)
                    .addComponent(btnAlterarOrdem))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnCadastrarNovoUsuario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarUsuario)
                    .addComponent(btnCadastrarOrdem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirUsuario)
                    .addComponent(btnListarOrdem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarUsuarios)
                    .addComponent(btnAlterarOrdem))
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        JSONObject json = new JSONObject();
        json.put("operacao", "logout");
        json.put("token", token);
        
        enviarJson(json);
        JSONObject respostaJson = receberJson();
        
        if (respostaJson.getString("status").equals("sucesso")){
            JOptionPane.showMessageDialog(this, "Logout bem sucedido", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            TelaInicial telaInicial = new TelaInicial(socket, output, input);
            telaInicial.setVisible(true);
            this.setVisible(false);
        } else if (respostaJson.getString("status").equals("erro")){
            JOptionPane.showMessageDialog(this, respostaJson.getString("mensagem"), "erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCadastrarOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarOrdemActionPerformed
        TelaCadastroOrdem telaCadastroOrdem = new TelaCadastroOrdem(socket, output, input, token, perfil);
        telaCadastroOrdem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCadastrarOrdemActionPerformed

    private void btnListarOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarOrdemActionPerformed
        TelaListarOrdem telaListarOrdem = new TelaListarOrdem(socket, output, input, token, perfil);
        telaListarOrdem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnListarOrdemActionPerformed

    private void btnAlterarOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarOrdemActionPerformed
        telaAlterarOrdem telAlterarOrdem = new telaAlterarOrdem(socket, output, input, token, perfil);
        telAlterarOrdem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAlterarOrdemActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void enviarJson(JSONObject json){
        output.println(json.toString());
        System.out.println("Json enviado: " + json.toString());
    }
    
    private JSONObject receberJson(){
        String resposta;
        try {
            resposta = input.readLine();
            JSONObject respostaJson = new JSONObject(resposta);
            System.out.println("Json recebido: " + respostaJson.toString());
            return respostaJson;
        } catch (IOException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarOrdem;
    private javax.swing.JButton btnCadastrarNovoUsuario;
    private javax.swing.JButton btnCadastrarOrdem;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.JButton btnListarOrdem;
    private javax.swing.JButton btnListarUsuarios;
    private javax.swing.JButton btnLogout;
    // End of variables declaration//GEN-END:variables
}
